builds:
  - goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

nfpms:
  - package_name: linkquisition
    homepage: https://www.strobotti.com
    maintainer: Juha Jantunen <juha@strobotti.com>
    description: |-
      Linkquisition is a browser-picker tool for opening links in a specific browser.
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    priority: optional

sboms:
  - artifacts: archive
