version: 2

git:
  # Allow dirty state because Wayland protocol headers are generated in CI
  # and not committed to the repository.
  allow_dirty: true

builds:
  - id: "application"
    binary: "linkquisition"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "unwrap-plugin"
    binary: "plugins/unwrap.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/unwrap/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "terminus-plugin"
    binary: "plugins/terminus.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/terminus/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "sanitize-plugin"
    binary: "plugins/sanitize.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/sanitize/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "defang-plugin"
    binary: "plugins/defang.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/defang/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "shenanigans-plugin"
    binary: "plugins/shenanigans.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/shenanigans/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

nfpms:
  - package_name: linkquisition
    homepage: https://github.com/Strobotti/linkquisition
    maintainer: Juha Jantunen <juha@strobotti.com>
    description: |-
      Linkquisition is a browser-picker tool for opening links in a specific browser.
    formats:
      - deb
      - rpm
    priority: optional
    section: utils
    dependencies:
      - libgl1
    contents:
      - src: ./dist/unwrap-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/unwrap.so
        dst: /usr/lib/linkquisition/plugins/unwrap.so
      - src: ./dist/terminus-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/terminus.so
        dst: /usr/lib/linkquisition/plugins/terminus.so
      - src: ./dist/sanitize-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/sanitize.so
        dst: /usr/lib/linkquisition/plugins/sanitize.so
      - src: ./dist/defang-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/defang.so
        dst: /usr/lib/linkquisition/plugins/defang.so
      - src: ./dist/shenanigans-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/shenanigans.so
        dst: /usr/lib/linkquisition/plugins/shenanigans.so
      - src: package/linux
        dst: /
        type: tree

sboms:
  - artifacts: archive
