builds:
  - id: "application"
    binary: "linkquisition"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "unwrap-plugin"
    binary: "plugins/unwrap.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/unwrap/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

  - id: "terminus-plugin"
    binary: "plugins/terminus.so"
    buildmode: plugin
    no_main_check: true
    goos:
      - linux
    goarch:
      - amd64
    main: ./plugins/terminus/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

nfpms:
  - meta: true
    package_name: linkquisition
    homepage: https://www.strobotti.com
    maintainer: Juha Jantunen <juha@strobotti.com>
    description: |-
      Linkquisition is a browser-picker tool for opening links in a specific browser.
    formats:
      - deb
      - rpm
    priority: optional
    dependencies:
      - libgl1
    contents:
      - src: ./dist/application_{{ .Os }}_{{ .Arch }}_v1/linkquisition
        dst: /usr/bin/linkquisition
      - src: ./dist/unwrap-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/unwrap.so
        dst: /usr/lib/linkquisition/plugins/unwrap.so
      - src: ./dist/terminus-plugin_{{ .Os }}_{{ .Arch }}_v1/plugins/terminus.so
        dst: /usr/lib/linkquisition/plugins/terminus.so
      - src: package/linux
        dst: /
        type: tree

sboms:
  - artifacts: archive
