package main

import (
	"bufio"
	"context"
	"encoding/base64"
	"fmt"
	"html/template"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/mitchellh/mapstructure"

	"github.com/strobotti/linkquisition"
)

// defaultSources is the list of blocklist URLs used when no custom sources are configured
var defaultSources = []string{
	"https://urlhaus.abuse.ch/downloads/hostfile/",
	"https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
}

// warningPageTemplate is the HTML template shown when a blocked URL is intercepted
var warningPageTemplate = template.Must(template.New("warn").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>⚠️ Linkquisition — Blocked URL</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 600px; margin: 80px auto; padding: 0 20px; color: #333; background: #fafafa; }
  .card { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 32px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
  h1 { color: #c0392b; margin-top: 0; font-size: 1.4em; }
  .domain { font-family: monospace; background: #fee; padding: 2px 6px; border-radius: 3px; color: #c0392b; }
  .url { word-break: break-all; font-family: monospace; font-size: 0.85em; background: #f5f5f5; padding: 8px; border-radius: 4px; margin: 12px 0; }
  .actions { margin-top: 24px; display: flex; gap: 12px; }
  .btn { padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: 500; cursor: pointer; border: none; font-size: 0.95em; }
  .btn-safe { background: #27ae60; color: #fff; }
  .btn-proceed { background: #e0e0e0; color: #555; font-size: 0.85em; }
  .btn-proceed:hover { background: #ccc; }
  .info { margin-top: 16px; font-size: 0.8em; color: #888; }
</style>
</head>
<body>
<div class="card">
  <h1>⚠️ Blocked by Linkquisition</h1>
  <p>The domain <span class="domain">{{.Domain}}</span> was found on a malware/phishing blocklist.</p>
  <div class="url">{{.URL}}</div>
  <div class="actions">
    <a href="about:blank" class="btn btn-safe">Close</a>
    {{if .ShowProceed}}<a href="{{.URL}}" class="btn btn-proceed">Open anyway (unsafe)</a>{{end}}
  </div>
  <p class="info">This page was generated by the Linkquisition defang plugin.</p>
</div>
</body>
</html>
`))

// DefangPluginSettings holds the configuration for the defang plugin
type DefangPluginSettings struct {
	// Sources is a list of URLs to download blocklists from (hosts-file format)
	Sources []string `json:"sources,omitempty"`

	// UpdateInterval is how often the blocklists should be refreshed (default: "168h" = 7 days)
	UpdateInterval string `json:"updateInterval,omitempty"`

	// Action determines what happens when a blocked URL is detected: "warn", "block", or "log"
	Action string `json:"action,omitempty"`
}

var _ linkquisition.Plugin = (*defang)(nil)

// defang is a plugin that checks URLs against known-malicious domain blocklists
type defang struct {
	settings        DefangPluginSettings
	sources         []string
	updateInterval  time.Duration
	action          string
	blockedDomains  map[string]struct{}
	cacheDir        string
	serviceProvider linkquisition.PluginServiceProvider

	mu       sync.Mutex
	updating bool
	done     chan struct{}
}

func (p *defang) Setup(serviceProvider linkquisition.PluginServiceProvider, config map[string]interface{}) {
	p.serviceProvider = serviceProvider
	p.blockedDomains = make(map[string]struct{})
	p.action = "block"
	p.updateInterval = 168 * time.Hour // 7 days
	p.sources = defaultSources

	var settings DefangPluginSettings
	if err := mapstructure.Decode(config, &settings); err != nil {
		serviceProvider.GetLogger().Warn("error decoding settings", "error", err.Error(), "plugin", "defang")
	} else {
		p.settings = settings

		if len(settings.Sources) > 0 {
			p.sources = settings.Sources
		}

		if settings.UpdateInterval != "" {
			if d, err := time.ParseDuration(settings.UpdateInterval); err != nil {
				serviceProvider.GetLogger().Warn(
					"invalid updateInterval",
					"error", err.Error(),
					"plugin", "defang",
				)
			} else {
				p.updateInterval = d
			}
		}

		if settings.Action != "" {
			switch settings.Action {
			case "warn", "block", "log":
				p.action = settings.Action
			default:
				serviceProvider.GetLogger().Warn(
					fmt.Sprintf("unknown action: %s, using 'block'", settings.Action),
					"plugin", "defang",
				)
			}
		}
	}

	// Set up cache directory next to config
	p.cacheDir = filepath.Join(serviceProvider.GetConfigFolderPath(), "defang")

	// Load cached blocklists from disk
	p.loadCachedLists()

	// Check if any lists need updating and start background fetch
	p.maybeStartUpdate()
}

func (p *defang) ModifyUrl(address string) string {
	parsed, err := url.Parse(address)
	if err != nil {
		return address
	}

	host := strings.ToLower(parsed.Hostname())
	if host == "" {
		return address
	}

	if !p.isDomainBlocked(host) {
		return address
	}

	p.serviceProvider.GetLogger().Warn(
		fmt.Sprintf("blocked URL: %s (domain %s is on blocklist)", address, host),
		"plugin", "defang",
		"action", p.action,
	)

	switch p.action {
	case "block":
		return p.generateWarningPage(address, host, false)
	case "log":
		// Log but still open the URL
		return address
	case "warn":
		return p.generateWarningPage(address, host, true)
	default:
		return p.generateWarningPage(address, host, false)
	}
}

// warningPageData holds the data passed to the warning page template
type warningPageData struct {
	Domain      string
	URL         string
	ShowProceed bool
}

// generateWarningPage creates a temporary HTML file with a warning/block page and returns its file:// URL
func (p *defang) generateWarningPage(originalURL string, domain string, showProceed bool) string {
	// Use a deterministic filename based on the URL to avoid accumulating temp files
	// for repeated clicks on the same link
	encoded := base64.RawURLEncoding.EncodeToString([]byte(originalURL))
	if len(encoded) > 64 {
		encoded = encoded[:64]
	}
	fileName := fmt.Sprintf("linkquisition-defang-%s.html", encoded)
	filePath := filepath.Join(os.TempDir(), fileName)

	file, err := os.Create(filePath)
	if err != nil {
		p.serviceProvider.GetLogger().Warn("error creating warning page", "error", err.Error(), "plugin", "defang")
		return "about:blank"
	}
	defer file.Close()

	data := warningPageData{
		Domain:      domain,
		URL:         originalURL,
		ShowProceed: showProceed,
	}

	if err := warningPageTemplate.Execute(file, data); err != nil {
		p.serviceProvider.GetLogger().Warn("error rendering warning page", "error", err.Error(), "plugin", "defang")
		return "about:blank"
	}

	return "file://" + filePath
}

func (p *defang) Shutdown(ctx context.Context) {
	p.mu.Lock()
	updating := p.updating
	done := p.done
	p.mu.Unlock()

	if !updating || done == nil {
		return
	}

	p.serviceProvider.GetLogger().Debug("waiting for blocklist update to finish", "plugin", "defang")

	select {
	case <-done:
		p.serviceProvider.GetLogger().Debug("blocklist update finished", "plugin", "defang")
	case <-ctx.Done():
		p.serviceProvider.GetLogger().Warn("blocklist update timed out during shutdown", "plugin", "defang")
	}
}

// isDomainBlocked checks if a domain or any of its parent domains are in the blocklist
func (p *defang) isDomainBlocked(host string) bool {
	p.mu.Lock()
	defer p.mu.Unlock()

	// Check the exact domain and all parent domains
	parts := strings.Split(host, ".")
	for i := range parts {
		domain := strings.Join(parts[i:], ".")
		if _, ok := p.blockedDomains[domain]; ok {
			return true
		}
	}

	return false
}

// loadCachedLists loads blocklists from the cache directory
func (p *defang) loadCachedLists() {
	if _, err := os.Stat(p.cacheDir); os.IsNotExist(err) {
		return
	}

	entries, err := os.ReadDir(p.cacheDir)
	if err != nil {
		p.serviceProvider.GetLogger().Warn("error reading cache directory", "error", err.Error(), "plugin", "defang")
		return
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}

		filePath := filepath.Join(p.cacheDir, entry.Name())
		p.loadHostsFile(filePath)
	}

	p.serviceProvider.GetLogger().Debug(
		fmt.Sprintf("loaded %d blocked domains from cache", len(p.blockedDomains)),
		"plugin", "defang",
	)
}

// loadHostsFile parses a hosts-format file and adds domains to the blocklist
func (p *defang) loadHostsFile(path string) {
	file, err := os.Open(path)
	if err != nil {
		p.serviceProvider.GetLogger().Warn("error opening hosts file", "path", path, "error", err.Error(), "plugin", "defang")
		return
	}
	defer file.Close()

	p.parseHostsReader(file)
}

// parseHostsReader parses a hosts-format reader and adds domains to the blocklist
func (p *defang) parseHostsReader(reader io.Reader) {
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Hosts file format: "0.0.0.0 domain.com" or "127.0.0.1 domain.com"
		fields := strings.Fields(line)
		if len(fields) < 2 { //nolint:mnd
			continue
		}

		ip := fields[0]
		if ip != "0.0.0.0" && ip != "127.0.0.1" {
			continue
		}

		domain := strings.ToLower(fields[1])

		// Skip localhost entries
		if domain == "localhost" || domain == "localhost.localdomain" ||
			domain == "local" || domain == "broadcasthost" ||
			domain == "ip6-localhost" || domain == "ip6-loopback" {
			continue
		}

		p.blockedDomains[domain] = struct{}{}
	}
}

// maybeStartUpdate checks if any cached list is stale and starts a background update
func (p *defang) maybeStartUpdate() {
	needsUpdate := false

	if _, err := os.Stat(p.cacheDir); os.IsNotExist(err) {
		// No cache at all — need to fetch
		needsUpdate = true
	} else {
		// Check if any source file is missing or older than updateInterval
		for i := range p.sources {
			fileName := fmt.Sprintf("source_%d.txt", i)
			filePath := filepath.Join(p.cacheDir, fileName)

			info, err := os.Stat(filePath)
			if err != nil || time.Since(info.ModTime()) > p.updateInterval {
				needsUpdate = true
				break
			}
		}
	}

	if !needsUpdate {
		return
	}

	p.mu.Lock()
	p.updating = true
	p.done = make(chan struct{})
	p.mu.Unlock()

	go p.fetchUpdates()
}

// fetchUpdates downloads all configured blocklist sources to the cache directory
func (p *defang) fetchUpdates() {
	defer func() {
		p.mu.Lock()
		p.updating = false
		close(p.done)
		p.mu.Unlock()
	}()

	p.serviceProvider.GetLogger().Debug("starting blocklist update", "plugin", "defang")

	if err := os.MkdirAll(p.cacheDir, 0700); err != nil {
		p.serviceProvider.GetLogger().Warn("error creating cache directory", "error", err.Error(), "plugin", "defang")
		return
	}

	client := &http.Client{
		Timeout: 30 * time.Second,
	}

	for i, source := range p.sources {
		fileName := fmt.Sprintf("source_%d.txt", i)
		filePath := filepath.Join(p.cacheDir, fileName)

		if err := p.downloadSource(client, source, filePath); err != nil {
			p.serviceProvider.GetLogger().Warn(
				fmt.Sprintf("error downloading blocklist from %s", source),
				"error", err.Error(),
				"plugin", "defang",
			)
			continue
		}

		// Load the newly downloaded list into memory
		p.loadHostsFile(filePath)
	}

	p.mu.Lock()
	domainCount := len(p.blockedDomains)
	p.mu.Unlock()

	p.serviceProvider.GetLogger().Debug(
		fmt.Sprintf("blocklist update complete, %d domains blocked", domainCount),
		"plugin", "defang",
	)
}

// downloadSource downloads a single blocklist source to a file
func (p *defang) downloadSource(client *http.Client, sourceURL string, destPath string) error {
	resp, err := client.Get(sourceURL)
	if err != nil {
		return fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d from %s", resp.StatusCode, sourceURL)
	}

	tmpPath := destPath + ".tmp"
	file, err := os.Create(tmpPath)
	if err != nil {
		return fmt.Errorf("error creating temp file: %w", err)
	}

	if _, err := io.Copy(file, resp.Body); err != nil {
		file.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("error writing file: %w", err)
	}

	file.Close()

	// Atomic rename
	if err := os.Rename(tmpPath, destPath); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("error renaming temp file: %w", err)
	}

	return nil
}

var Plugin = &defang{}

// NewForTesting creates a fresh defang instance for use in tests (avoids mutex copy issues with the global Plugin var)
func NewForTesting() linkquisition.Plugin {
	return &defang{}
}
